### PR TITLE
NEW: Write CUDA kernels for USFFT gather scatter operation

### PR DESCRIPTION
**Pull request by carterbox**
## Purpose

Improve the speed of the laminography operator by replacing slow parts of the USFFT operation with CUDA kernels. 

## Approach

Targeted the scatter and gathering loops in the USFFT because these sections have tight Python loops (which are slow). These loops are now inside a CUDA kernel. We still use atomic operations because avoiding them means using less parallelism (using fewer threads) and/or doing more operations (looping over all grid points instead of only kernel grid points).

Results of the operators tests change, but they still pass because 3 sig. figs. are the same.

### Submitter
- [x] Write a helpfully descriptive pull request title.
- [x] Organize changes into logically grouped commits with descriptive commit messages.
- [ ] Document all new functions.
- [x] Write tests for new functions or explain why they are not needed.
- [ ] Build the documentation successfully
- [ ] Use [`yapf`](https://github.com/google/yapf) to format python code.

### Reviewer
- [ ] Actually read all of the code.
- [ ] Run the new code yourself.
- [ ] Write a summary of the changes as you understand them.
- [ ] Thank the submitter.

### CODE REVIEW

**Comment by nikitinvv** [comment]
> We still use atomic operations because avoiding them means using less parallelism (using fewer threads) and/or doing more operations (looping over all grid points instead of only kernel grid points).

atomic operations can be avoided without having these problems.

**Comment by carterbox** [comment]
If you could explain how, I'd love to hear about it, but also, if removing atomic operations isn't going to improve the runtime by another order of magnitude, then we should save it for later.

**Comment by nikitinvv** [comment]
What is the current difference in times for fwd and adj laminography operators? for some real sizes.

**Comment by carterbox** [comment]
With you requested data size of 300 angles and 256^3 object. The memory footprint was 6395 MiB. The operators were too fast to profile for a single call:
```
1.020 test_adjoint  operators/test_lamino.py:30
└─ 1.011 adj  tike/operators/cupy/lamino.py:51
      [18 frames hidden]  tike, cupy, ..
         1.010 us2eq  tike/operators/numpy/usfft.py:174
         └─ 1.007 [self]  
```
Looped through the forward and adjoint operator 50 times to improve statistics:
```
88.932 test_adjoint  operators/test_lamino.py:30
├─ 51.225 adj  tike/operators/cupy/lamino.py:51
│     [135 frames hidden]  tike, cupy, genericpath, .., numpy, abc
│        51.115 us2eq  tike/operators/numpy/usfft.py:174
│        └─ 50.183 [self]  
└─ 37.708 fwd  tike/operators/cupy/lamino.py:27
      [181 frames hidden]  tike, cupy, .., numpy, genericpath, s...
         36.784 eq2us  tike/operators/numpy/usfft.py:72
         └─ 36.099 [self]  
```
Looks like adjoint operator takes twice the time of the forward operation, Most of the time is spent inside the USFFT functions, but not in any child functions. That means lines like these?:
```python
    ndim = f.ndim
    pad = n // 2  # where zero-padding stops
    end = pad + n  # where f stops
    mu = -xp.log(eps) / (2 * n**2)
    Te = 1 / xp.pi * xp.sqrt(-mu * xp.log(eps) + (mu * n)**2 / 4)
    m = xp.int(xp.ceil(2 * n * Te))
    fe[pad:end, pad:end, pad:end] = f / ((2 * n)**ndim * kernel)
```
After memory profiling. I suggest that we make the USFFT a tike.Operator class, so that we can cache these constants or make something like the `FFTplan` object that CUDA uses.

**Comment by carterbox** [comment]
That said, refactoring as a class and improving memory footprint are beyond the scope of this PR.

**Comment by nikitinvv** [comment]
@carterbox times for fwd and adj look good! But it looks strange that constant computations take some time. This should not happen. This is just my suggestion of a possible reason:
Do you know that cuda kernels are asynchronous calls (cpu starts the gpu kernel and go to next code lines immediately)? which means that for measuring their times correctly you should synchronize cpu and gpu after the call. Otherwise, the profiler measures this time later and associate it with some next cpu code call. In matlab this synchronization command is wait(gpu), maybe python also have something. Another option is to look at nvidia-visual profiler results.

**Comment by nikitinvv** [comment]
and a straightforward option is to profile the code with commented kernels

**Comment by carterbox** [comment]
OK. This time I used `nvprof` on my personal computer. It required `sudo`, so I don't think I have permission to use it on lab-owned hardware? Anyways, here's function calls that took more than 1% of runtime for the adjoint operator test:
```
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:   55.51%  18.2833s        10  1.82833s  1.80698s  1.88471s  gather
                   35.23%  11.6036s        10  1.16036s  1.15437s  1.16309s  scatter
                    3.61%  1.18981s       510  2.3330ms  99.804us  13.679ms  cupy_copy__complex64_complex64
                    1.40%  460.79ms        40  11.520ms  11.115ms  12.644ms  void composite_2way_fft<unsigned int=384, unsigned int=8, unsigned int=8, padding_t=0, twiddle_t=0, loadstore_modifier_t=2, unsigned int=12, layout_t=1, unsigned int, float>(kernel_arguments_t<unsigned int>)
                    1.05%  346.51ms       122  2.8402ms  4.5760us  4.6222ms  [CUDA memcpy DtoD]
```
This confirms that the new kernels are of the same order of magnitude and seem to dominate the computation time.

This was for 192^3 grid and 192 angles. Precision 1e-3.

**Comment by nikitinvv** [comment]
Thanks @carterbox

**Pull request merged**
