### PR TITLE
NEW: Multi-device multi-probe updates for ptycho.cgrad

### PR DESCRIPTION
**Pull request by carterbox**
## Purpose

Add multi-device probe updates to the ptycho.cgrad method.

## Approach

Uses features enabled by the refactoring of the `Patch` operator to update all probes simultaneously using multiple devices.

### Submitter
- [x] Write a helpfully descriptive pull request title.
- [x] Organize changes into logically grouped commits with descriptive commit messages.
- [ ] Document all new functions.
- [x] Write tests for new functions or explain why they are not needed.
- [ ] Build the documentation successfully
- [x] Use [`yapf`](https://github.com/google/yapf) to format python code.

### Reviewer
- [ ] Actually read all of the code.
- [ ] Run the new code yourself.
- [ ] Write a summary of the changes as you understand them.
- [ ] Thank the submitter.

### CODE REVIEW

**Comment by xiaodong-yu** [comment]
Does this PR use different devices to process different probes? If so, we need to schedule a meeting with Tekin, possibly tomorrow. We need to discuss the priority between the sub-images and the probes in terms of device usage.

**Comment by carterbox** [comment]
No. It only divides the work along the scan-position-axis. It doesn't make sense to split the probes between different devices because that would probably require synchronizing diffraction patterns between devices.

**Comment by xiaodong-yu** [comment]
> No. It only divides the work along the scan-position-axis. It doesn't make sense to split the probes between different devices because that would probably require synchronizing diffraction patterns between devices.

Then, it's confusing to me what does "update all probes simultaneously using multiple devices" mean?

**Comment by carterbox** [comment]
When multi-probe is enabled (the number of probes (modes) is greater than 1), each of the these probes is updated simultaneously with the others instead of sequentially.

**Comment by xiaodong-yu** [comment]
But each device will process all the probes, just with different scans, right?

**Comment by carterbox** [comment]
That is correct.

**Review by xiaodong-yu — APPROVED** [review]

**Pull request merged**
