### PR TITLE
NEW: Add some probe initialization and orthogonalization tools

### PR DESCRIPTION
**Pull request by carterbox**
## Purpose
Provide some Python probe initialization and orthogonalization routines that the Swiss are using in their MATLAB code.

### Submitter
- [x] Write a helpfully descriptive pull request title.
- [x] Organize changes into logically grouped commits with descriptive commit messages.
- [x] Document all new functions.
- [ ] Write tests for new functions or explain why they are not needed.
- [ ] Build the documentation successfully
- [x] Use [`yapf`](https://github.com/google/yapf) to format python code.

### Reviewer
- [ ] Actually read all of the code.
- [ ] Run the new code yourself.
- [ ] Write a summary of the changes as you understand them.
- [ ] Thank the submitter.

### CODE REVIEW

**Comment by nikitinvv** [comment]
# Perhaps this should be an inner product
            # which means one of the vectors should be conjugated?
            A[i, j] = np.sum(x[i] * x[j])
            A[j, i] = A[i, j]

 yes, one should be conjugate

**Comment by nikitinvv** [comment]
for order in np.argsort(-values):
        x_sorted[order] = x_new[order]

indices are wrong

**Comment by carterbox** [comment]
> indices are wrong

@nikitinvv, why are they wrong?

**Comment by carterbox** [comment]
Thanks, @nikitinvv! 🎉

**Pull request merged**
